version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/springbootUnittest
hooks:
  BeforeInstall:
    - location: scripts/bootStrap.sh
  ApplicationStart:
    - location: scripts/app_start.sh
  AfterInstall:
    - location: scripts/build.sh