version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/spring-boot-vuejs
hooks:
  ApplicationStart:
    - location: scripts/app_start.sh
  AfterInstall:
      - location: scripts/build.sh